# Generated by Django 6.0.5 on 2026-06-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('is_review_crawled', models.BooleanField(default=False)),
                ('valence', models.FloatField(blank=True, null=True)),
                ('arousal', models.FloatField(blank=True, null=True)),
                ('joy', models.FloatField(blank=True, null=True)),
                ('sadness', models.FloatField(blank=True, null=True)),
                ('anger', models.FloatField(blank=True, null=True)),
                ('fear', models.FloatField(blank=True, null=True)),
                ('trust', models.FloatField(blank=True, null=True)),
                ('surprise', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
