# Generated by Django 6.0.5 on 2026-06-07 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('music_movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('weather', models.CharField(blank=True, choices=[('SUNNY', '맑음'), ('CLOUDY', '흐림'), ('RAINY', '비'), ('SNOWY', '눈'), ('WINDY', '바람'), ('THUNDER', '천둥')], help_text='일기 작성 당시 날씨', max_length=10, null=True)),
                ('image', models.ImageField(blank=True, help_text='일기에 첨부된 사진', null=True, upload_to='diaries/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiaryEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joy', models.FloatField(default=0.0, help_text='기쁨 감정 점수 (0.0에서 1.0 사이)')),
                ('sadness', models.FloatField(default=0.0, help_text='슬픔 감정 점수 (0.0에서 1.0 사이)')),
                ('anger', models.FloatField(default=0.0, help_text='분노 감정 점수 (0.0에서 1.0 사이)')),
                ('fear', models.FloatField(default=0.0, help_text='두려움 감정 점수 (0.0에서 1.0 사이)')),
                ('trust', models.FloatField(default=0.0, help_text='신뢰 감정 점수 (0.0에서 1.0 사이)')),
                ('surprise', models.FloatField(default=0.0, help_text='놀람 감정 점수 (0.0에서 1.0 사이)')),
                ('valence', models.FloatField(help_text='감정의 긍정/부정 정도를 나타내는 값 (-1.0에서 1.0 사이)')),
                ('arousal', models.FloatField(help_text='감정의 활성화 정도를 나타내는 값 (-1.0에서 1.0 사이)')),
                ('primary_emotion', models.CharField(default='알수없음', help_text='대표 감정 단어', max_length=50)),
                ('diary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion', to='diary.diary')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='maintain', help_text='추천이 생성된 감정 모드', max_length=20)),
                ('is_book_fallback', models.BooleanField(default=False)),
                ('is_music_fallback', models.BooleanField(default=False)),
                ('is_movie_fallback', models.BooleanField(default=False)),
                ('books', models.ManyToManyField(blank=True, related_name='daily_recommendations', to='books.book')),
                ('movies', models.ManyToManyField(blank=True, related_name='daily_recommendations', to='music_movie.movie')),
                ('musics', models.ManyToManyField(blank=True, related_name='daily_recommendations', to='music_movie.music')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='diary.diary')),
            ],
            options={
                'unique_together': {('diary', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=7)),
                ('object_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'feedback_type', 'created_at'], name='diary_userf_user_id_bf2c55_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
